<h3>Erkl&aelig;ring</h3>
<p><a href="http://www.dosspirit.net">The DOS Spirit</a> hedrer de gode gamle dager for DOS-spill enten husker eller ei, hater eller elsker. Her hos oss tilbyr vi v&aring;re bes&oslash;kende en mulighet til &aring; gjenoppleve disse minnene, minner som aldri m&aring; glemmes. Vi omtaler hver tittel med bakgrunnsinformasjon og andre interessante emner relatert til titlene, herunder nedlasting av dem. Disse g&aring;r under kategorien &quot;<a href="http://en.wikipedia.org/wiki/Abandonware" target="_blank">Abandonware</a>&quot;, og vi har inget eierskap av disse titlene og heller tar vi aldri betalt for noe av dette. </p>
<p>Vi eksisterer av den enkle grunn av at det temaet vi befatter oss rundt har hatt stor innflytelse p&aring; oss som barn, og dette er en m&aring;te &aring; hedre de gamle klassikerene p&aring; en m&aring;te vi synes er passende. Nedlastingene skjer p&aring; eget ansvar og per definisjon m&aring; du selv eie en kopi av spillet for titler som er under ESA. De titlene som fortsatt selges tilbyr vi demoversjonen, samt at alle har en kj&oslash;pelenke hvor du kan skaffe deg din helt egne kopi til en liten slump. </p>
<p>Essensen ligger likevel i at mange av disse titlene har for lengst blitt glemt, og st&oslash;ttes ikke lenger av sine respektive hovedinnehavere. Vi &oslash;nsker &aring; ta vare p&aring; disse minnene ved &aring; tilby en &quot;renesanse&quot; av dem til v&aring;re bes&oslash;kende, slik at de kan hedres som de seg h&oslash;r og b&oslash;r. Sidene v&aring;re er innholdsvennlige ovenfor alle aldersgrupper, slik at eventuelle bekymrede foreldre kan trygt slippe barna rundt p&aring; sidene v&aring;re.</p>
<p>Om innehavere av noen av de titlene vi omtaler &oslash;nsker filene relatert til dem fjernet, ber vi de om &aring; kontakte oss og vi vil fjerne det respektive programmet umiddelbart.

  <a href="http://www.dosspirit.net">The DOS Spirit</a> er et prosjekt som ble startet i 2004 av innehaver bakkelun, men da under navnet &quot;bakkelun - the Good Old DOS Spirit&quot;. Vi endret navn til The DOS Spirit i 2005, og vi feiret 2&aring;rs-jubileum for en tid tilbake. <br />
</p>
<h3>Disclaimer</h3>
<p><a href="http://www.dosspirit.net">The DOS Spirit</a> honors the good old days for DOS-games that everyone loves, and those few have heard of. We here at the site want to offer these good memories to our visitors, and give them a opportunity to relive these memories, memories that shall never be forgotten. Some of our titles fall under the so called &quot;<a href="http://en.wikipedia.org/wiki/Abandonware" target="_blank">Abandonware</a>&quot; category, which means that they're no longer supported by the original creators. We claim absolutely no ownership of the titles themselves, and will never charge anything for the service we provide. </p>
<p>We exist simply because what we do has influenced our childhoods immensely, and this is a way to tribute the old classics in a way be believe honors them. Downloads happen on your own responsibility and per definition you have to own a personal copy of titles that are under the ESA to rightfully download. For titles that are still sold, we offer a demo for download and a link as to where you can buy it for a tiny penny. </p>

<p>The essence in all this however is that many of the titles we offer here at <a href="http://www.dosspirit.net">The DOS Spirit</a> have long gone been &quot;abandoned&quot;, and no longer are supported by their rightful owners and creators. We wish to preserve these memories by offering a &quot;renaissance&quot; of them to our visitors, so they can be honored the way that's most appropriate. In addition, our pages are content friendly against all age-groups, which means that ancious parents can safely let their children use our pages.
If the creators of the titles we review wishes the files related to them removed, we kindly ask them to <a href="/contact">contact us</a> and we will remove the respective software immediately and with no discussion whatsoever. </p>

<a href="/contact">Kontakt oss / Contact us</a>