<h1>Støtt The Dos Spirit</h1>

The Dos Spirit er på mange måter et hobbyprosjekt, men samtidig et som tar mye tid. Vi gjør dette hovedsakelig av interesse av å bringe gode minner til folket verden rundt. Kanskje finner du noe du husker fra barndommen eller kanskje en og annen ukjent juvel?
 Hvis du setter pris på det vi gjør, har du muligheten til å støtte oss.
          Du kan velge hvilken doneringstype du ønsker. Vi har oppgitt valgene 1€, 5€ og 10€ som standard, men du kan også velge eget beløp. Donering
          er selvfølgelig valgfritt, men vi setter stor pris på å
          bli støttet for å holde kvaliteten og "DOS-ånden" vedlike.
          <p>
          </p><p>Donasjoner havner på forsiden i hva vi kaller "Golden Goblin's Hall of Fame" (Under arbeid).</p>
          Donasjoner skjer enten gjennom Flattr eller PayPal; en sikker
          og pålitelig overføringstjeneste som benyttes av millioner
          verden over. Du kan enkelt støtte oss ved å klikke knappen
        under (leder til ekstern lenke, paypal.com i et nytt vindu). Flattr-knappen gjør mye av jobben for deg, bare å trykke på knappen, logge inn og du er ferdig! <br>
        På forhånd takk!
        <p></p>
<h1>Support The DOS Spirit</h1>
          The DOS Spirit is in many ways a hobby project, but at the same time it takes ridicolous amounts of time to keep updated. We do this however of the common interest of sharing valued memories to the people around the world. Perhaps you'll find something you remember from your youth, or a hidden DOS gem?
          If you like what we do we encourage you to support The DOS Spirit with a donation. We've enlisted 1€, 5€ and 10€ as defaults, but you can specify your own amount if you like. Donation is of course voluntary, but donations encourage more frequent updates as well as a nice "thank  you" to the services.
          <p>Donators end up on the "Golden Goblin's Hall of Fame" on the first page (In progress).</p>
          <p>
          The donation-process is through PayPal or Flattr, and is a painless, secure and reliable partner that's used by
          millions of people around the world every day. You can easily support us by clicking the button
          below (it opens www.paypal.com, in a new window). The Flattr button does much of the work for you, just push the button, login and you're done!<br>
          Thanks!
          </p>


<h2>Velg nedenfor / Choose below</h2>
<div style="float:left; width: 180px; text-align: center;">
<form method="post" action="https://www.paypal.com/cgi-bin/webscr">
<input type="hidden" value="_s-xclick" name="cmd">
<input type="hidden" value="-----BEGIN PKCS7-----MIIHiAYJKoZIhvcNAQcEoIIHeTCCB3UCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCZEc5mcqp0MOLER+8UMMilg7dzl1bMQ6Qu78wKs3MSBQfjN4MhSXzjTfaKnEJsxckirn2WfTqeiapCUgCgqKPgNPnTcg50T3r21gb21UEXk9EUR5gGFJpasjuM+6OTVMMmdHo0NZqDy6z4XtPbmubSsBfI0KS40tpU7ewB3CTCgzELMAkGBSsOAwIaBQAwggEEBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECDBf78Z7VeGGgIHgCwzi/uOrYn2YYAc9jIsVcyBnYbS2JdUY9NCqmguaJK0LSM9QfY0IeLvvnTRtFQ3kDkjwhSGf2jAEJYFfVcVrt5IR6wtdCzRgkHttOlwbxbFjtWit+d7FA88O/SNWDaeUAKJ23oQCEfvUh7VnFA/Y/JE/H0MzS2mAHZRQqNVeegx7SoOVAztXcAUCXZWNa4bBy0h+5f0mEEEKteMUWNHSLf2woCjTQuia2O565stj+BgtmS/RxBuO1SgPC2hhyugp1q8WsmPI99TaPMRqxsXNOxWuhVHj64GH5nhbDcpC9eCgggOHMIIDgzCCAuygAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wHhcNMDQwMjEzMTAxMzE1WhcNMzUwMjEzMTAxMzE1WjCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMFHTt38RMxLXJyO2SmS+Ndl72T7oKJ4u4uw+6awntALWh03PewmIJuzbALScsTS4sZoS1fKciBGoh11gIfHzylvkdNe/hJl66/RGqrj5rFb08sAABNTzDTiqqNpJeBsYs/c2aiGozptX2RlnBktH+SUNpAajW724Nv2Wvhif6sFAgMBAAGjge4wgeswHQYDVR0OBBYEFJaffLvGbxe9WT9S1wob7BDWZJRrMIG7BgNVHSMEgbMwgbCAFJaffLvGbxe9WT9S1wob7BDWZJRroYGUpIGRMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbYIBADAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIFfOlaagFrl71+jq6OKidbWFSE+Q4FqROvdgIONth+8kSK//Y/4ihuE4Ymvzn5ceE3S/iBSQQMjyvb+s2TWbQYDwcp129OPIbD9epdr4tJOUNiSojw7BHwYRiPh58S1xGlFgHFXwrEBb3dgNbMUa+u4qectsMAXpVHnD9wIyfmHMYIBmjCCAZYCAQEwgZQwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tAgEAMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xMDA4MjEwMDI3MTVaMCMGCSqGSIb3DQEJBDEWBBSiboAN8VSd4M8mqctJnYtqaS0cDzANBgkqhkiG9w0BAQEFAASBgK5JGIlliVNU3Pkvqjz/SBKyqNaDoQbvaWI90d4qpxDhT2Owp7az897+lgOsq++ZBMk2u8Naaie2AOkBr2tyYdoSDVOuHNkr7HWAm0TL4pAjXfbSUvtRgNlxisfcm+kR5zqKLjNPQaudisFBXP2iKyZCmlpBxHhtq9H03cAkLDsc-----END PKCS7-----
" name="encrypted">
<input type="image" border="0" alt="PayPal - The safer, easier way to pay online!" name="submit" title="Donate 1 euro via Paypal. Thanks!" src="http://dosspirit.net/images/donate-1euro.png">
<img width="1" height="1" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" alt="">
</form>
</div>

<div style="float:left; width: 180px; text-align: center;">
<form method="post" action="https://www.paypal.com/cgi-bin/webscr">
<input type="hidden" value="_s-xclick" name="cmd">
<input type="hidden" value="-----BEGIN PKCS7-----MIIHiAYJKoZIhvcNAQcEoIIHeTCCB3UCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYBXuNx9scqi7A7hiJlNMsNTZB86ISIRuF+Lc9XenWUTdkRZfLWvJg9FsMgPl6tVrd3KxqO1ncJD0ks2FrEHi7BXJN2z3TnO2oLV1ougRcL27EGQ+61Tdx6fGEamjlaJKLINpdGPUY2JW2tp2ktDgEo2xZwyUDhyCqmCh0DNqiSJeTELMAkGBSsOAwIaBQAwggEEBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECEN67n/4M0VzgIHgJCY30eyDFf9twvmEGGIJiBqy5l378PfrPU6agiBKY0agEYq2/GlYtYQwOCwPxnkbtpYBXw4n6DiXvHrP9GEFNh8WAG7i0u3Y6qnBBg2DTuT8SyjrumHPefS73ILWRlGzYY21VQD78octr8zxYC7HsAwtvtUQqvfrvAqNfZ9MSQ2PReZ43g/gbIDbCxWjWjaxn5+vAhpjoD4H2jEV6/9BwtW6fQFZcREzxkovggAj2a0y9JMCmeEfIPxmSVithj7OIgBD6Wfj7lCsf2lfjpEzF/uiuLIUgTo5AJ8GJ+QjgGSgggOHMIIDgzCCAuygAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wHhcNMDQwMjEzMTAxMzE1WhcNMzUwMjEzMTAxMzE1WjCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMFHTt38RMxLXJyO2SmS+Ndl72T7oKJ4u4uw+6awntALWh03PewmIJuzbALScsTS4sZoS1fKciBGoh11gIfHzylvkdNe/hJl66/RGqrj5rFb08sAABNTzDTiqqNpJeBsYs/c2aiGozptX2RlnBktH+SUNpAajW724Nv2Wvhif6sFAgMBAAGjge4wgeswHQYDVR0OBBYEFJaffLvGbxe9WT9S1wob7BDWZJRrMIG7BgNVHSMEgbMwgbCAFJaffLvGbxe9WT9S1wob7BDWZJRroYGUpIGRMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbYIBADAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIFfOlaagFrl71+jq6OKidbWFSE+Q4FqROvdgIONth+8kSK//Y/4ihuE4Ymvzn5ceE3S/iBSQQMjyvb+s2TWbQYDwcp129OPIbD9epdr4tJOUNiSojw7BHwYRiPh58S1xGlFgHFXwrEBb3dgNbMUa+u4qectsMAXpVHnD9wIyfmHMYIBmjCCAZYCAQEwgZQwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tAgEAMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xMDA4MjEwMDMwNTdaMCMGCSqGSIb3DQEJBDEWBBSuMdpWaehipWwbxUTVGj5D3peLDTANBgkqhkiG9w0BAQEFAASBgFExSqlxQq3BQgAmu/SnhfBJyeLbsQkdvKEXDhvUKwJOzcqvTDsQwek2DDBfTvFD9L9TOWAzQhMdJr3vKSWWt1v2BkIeWj4lgieT9K8bgnV7hrsEoATxOrDLk9gCaYy5hfyyU9692tfzXW+yrpT4G1WwP2HZU4Bz4cEWDp4doTWa-----END PKCS7-----
" name="encrypted">
<input type="image" border="0" alt="PayPal - The safer, easier way to pay online!" name="submit" title="Donate 5 euro via Paypal. More Thanks!" src="http://dosspirit.net/images/donate-5euro.png">
<img width="1" height="1" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" alt="">
</form>
</div>

<div style="float:left; width: 180px; text-align: center;">
<form method="post" action="https://www.paypal.com/cgi-bin/webscr">
<input type="hidden" value="_s-xclick" name="cmd">
<input type="hidden" value="-----BEGIN PKCS7-----MIIHiAYJKoZIhvcNAQcEoIIHeTCCB3UCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCkZ6apMrgm2/UDO610LVuatg1K/3ANU5RreN8MT6xk8jFkHC04/RKQDo0MhYJ22fiLE2/yhK5B4gsaFU6xGgaZTND/4/Zh6jDdXPpuxejrth2w2yShXN91EvI/nIC2hvKDO2L1pOuIT918/xYLWw0whHOSjPxa+UssgbXNO4ubrTELMAkGBSsOAwIaBQAwggEEBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECJKXnbNpjsGCgIHg/cQNSRDcn8WXA/ggEKzOOAXk4NJJwvwj3gfE382GpWk6g0eM/IujgoxEjwxpCHM4Nz3H9d3FbuGUXRCW4YkvtDaz080ZR9pcIF2ccpE7un2W/45wfHmUBrDHZl5Oi2dMXLxPpYKkf/HmNmxWS9NyviupLx/yYLr7ZSM1VzT0z4weLupilG7i6sqMTD1j8eCHNYZsjqIIbbAaj7T3uYG08lGOeowPDEkGYw9Zs0T53ISkAya6L0JhKz78WKGhl6iZl5+fslsjxR4KZjC/LakKo8QQ10Wzg1xtg6mRMIX9DtCgggOHMIIDgzCCAuygAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wHhcNMDQwMjEzMTAxMzE1WhcNMzUwMjEzMTAxMzE1WjCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMFHTt38RMxLXJyO2SmS+Ndl72T7oKJ4u4uw+6awntALWh03PewmIJuzbALScsTS4sZoS1fKciBGoh11gIfHzylvkdNe/hJl66/RGqrj5rFb08sAABNTzDTiqqNpJeBsYs/c2aiGozptX2RlnBktH+SUNpAajW724Nv2Wvhif6sFAgMBAAGjge4wgeswHQYDVR0OBBYEFJaffLvGbxe9WT9S1wob7BDWZJRrMIG7BgNVHSMEgbMwgbCAFJaffLvGbxe9WT9S1wob7BDWZJRroYGUpIGRMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbYIBADAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIFfOlaagFrl71+jq6OKidbWFSE+Q4FqROvdgIONth+8kSK//Y/4ihuE4Ymvzn5ceE3S/iBSQQMjyvb+s2TWbQYDwcp129OPIbD9epdr4tJOUNiSojw7BHwYRiPh58S1xGlFgHFXwrEBb3dgNbMUa+u4qectsMAXpVHnD9wIyfmHMYIBmjCCAZYCAQEwgZQwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tAgEAMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xMDA4MjEwMDMxNDlaMCMGCSqGSIb3DQEJBDEWBBQFntRdCi9eVOb2BKAaOkub5quW2TANBgkqhkiG9w0BAQEFAASBgMDnNzAN5MWQvYmkf2JTDkqfzg1/Q0RMq+JrcwfI2CqnjIaswcXLBiFg3qeKpkSkxaqAk5X9f4NzIwhjgxf3zC3q2yNIhjKVFcdSMsDJb5RyGpDRU4/J0Z7yfabXdf9/slFxOJPr9rUuUKKqAcP6YLxE6E6RX69DVhEnWQhDW0fs-----END PKCS7-----
" name="encrypted">
<input type="image" border="0" alt="PayPal - The safer, easier way to pay online!" name="submit" title="Donate 10 euro via Paypal. Super Thanks!" src="http://dosspirit.net/images/donate-10euro.png">
<img width="1" height="1" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" alt="">
</form>
</div>

<div style="float:left; width: 180px; text-align: center;">
<form method="post" action="https://www.paypal.com/cgi-bin/webscr">
<input type="hidden" value="_s-xclick" name="cmd">
<input type="hidden" value="-----BEGIN PKCS7-----MIIHfwYJKoZIhvcNAQcEoIIHcDCCB2wCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYAkuTNiKBXpA8b/rlSbCc0yYIlyZg75s3bF2YRPbi93fB3aimv3guEjHL2DbVv3TblDdGm2mdCqY7aiOSxBMptb9lwx3suRcDyQRylRRRj2xaOdg9OqABu+TKFn6bC68pa+5FkEotvwYCQVVHRJ9JBPD8uYTkPY38x+HNb1ee11VjELMAkGBSsOAwIaBQAwgfwGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIgRZmFw8Ip6uAgdh5cdPHN+ZmUQ3CgQbqVaegyUQirxyZuThGU0xB7aqi5PoTf+t7rzqy7feJ4HDw4bzHZi1evmxyWZVI1e7f9aHgG3VgH02u6XPwxOzcQ4URsOXzawvmnnuu8tWH2sWMkysCDSnTX/EXbg96mOrzgQYRlq1zzJXWfxwNolvFwPff3R+2Pb0imKSGsBfI97Ng83s/4xdfrEEID57ne5Rshjuc/d7dkMKp8GWtj2fqlxL/AsqQ0rAtfaTX/ggGPXW6yiWMfztWzOU/uJACOt1rNQEqdcUr2jFnPqCgggOHMIIDgzCCAuygAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wHhcNMDQwMjEzMTAxMzE1WhcNMzUwMjEzMTAxMzE1WjCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMFHTt38RMxLXJyO2SmS+Ndl72T7oKJ4u4uw+6awntALWh03PewmIJuzbALScsTS4sZoS1fKciBGoh11gIfHzylvkdNe/hJl66/RGqrj5rFb08sAABNTzDTiqqNpJeBsYs/c2aiGozptX2RlnBktH+SUNpAajW724Nv2Wvhif6sFAgMBAAGjge4wgeswHQYDVR0OBBYEFJaffLvGbxe9WT9S1wob7BDWZJRrMIG7BgNVHSMEgbMwgbCAFJaffLvGbxe9WT9S1wob7BDWZJRroYGUpIGRMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbYIBADAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIFfOlaagFrl71+jq6OKidbWFSE+Q4FqROvdgIONth+8kSK//Y/4ihuE4Ymvzn5ceE3S/iBSQQMjyvb+s2TWbQYDwcp129OPIbD9epdr4tJOUNiSojw7BHwYRiPh58S1xGlFgHFXwrEBb3dgNbMUa+u4qectsMAXpVHnD9wIyfmHMYIBmjCCAZYCAQEwgZQwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tAgEAMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xMDA4MjEwMDM1MzJaMCMGCSqGSIb3DQEJBDEWBBTEQPvrFf7eP1mKBipdGVdlM1CVzjANBgkqhkiG9w0BAQEFAASBgJZe4TT2PoFn3V1z6jN3We6DzXESMGhIbXUDOKokN/U+euY6lZlbzWaVBKw95nmayF5iXlECYiZQasXSYvt/ku01CtIClqNUXO10j3+3gzjT+hqE0e4kGT1guM18P/0RZVh3TlijCFEAZH52J15TUsluwlwOQOSxOtqxSsfJobrA-----END PKCS7-----
" name="encrypted">
<input type="image" border="0" alt="PayPal - The safer, easier way to pay online!" name="submit" src="http://dosspirit.net/images/donate-chooseamount.png">
<img width="1" height="1" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" alt="">
</form>
</div>

<div style="float:left; width: 180px; text-align: center;">
<iframe width="55" scrolling="no" height="62" frameborder="0" src="http://api.flattr.com/button/view/?url=http%3A%2F%2Fwww.dosspirit.net%2F&amp;" class="FlattrButton" border="0" marginheight="0" marginwidth="0" allowtransparency="true"></iframe><br>
Support us via Flattr!
</div>

<div class="clearer"></div>
<p><em>Buttons link to www.paypal.com, which is a secure way to transfer money online.</em></p>